### ISSUE TITLE
Error: LoadError: Method Error 

### ISSUE THREAD

**Issue by marzaidi** [kharchenkolab/Baysor#139] opened 2024-09-24 12:57 UTC
i keep getting this error when i execute baysor run: 

ERROR: LoadError: MethodError: no method matching tryparse(::Type{Symbol}, ::String)

Closest candidates are:
  tryparse(::Type{Union{}}, ::Any...; kwargs...)
   @ Base parse.jl:257
  tryparse(::Type{FilePathsBase.PosixPath}, ::AbstractString)
   @ FilePathsBase ~/.julia/packages/FilePathsBase/Laclt/src/posix.jl:15
  tryparse(::Type{Float16}, ::AbstractString)
   @ Base parse.jl:302
  ...

Stacktrace:
 [1] command_main(ARGS::Vector{String})
   @ Baysor ~/.julia/packages/Comonicon/F3QqZ/src/codegen/julia.jl:490
 [2] command_main()
   @ Baysor ~/.julia/packages/Comonicon/F3QqZ/src/codegen/julia.jl:90
 [3] top-level scope
   @ ~/.julia/bin/baysor:15

**Comment by VPetukhov** [comment] 2024-09-24 14:16
Looks like a duplicate of https://github.com/kharchenkolab/Baysor/issues/138 .

Same as there, please, provide more information. The OS, the command you ran and full error stacktrace and full log.

**Comment by marzaidi** [comment] 2024-09-25 11:10
OS: 
Linux cm2login1 4.12.14-197.108-default #1 SMP Tue Mar 1 18:11:35 UTC 2022 (2b1bf36) x86_64 x86_64 x86_64 GNU/Linux

Command:
baysor run -x x_location -y y_location -z z_location -g feature_name -m 15 '~/transcripts.csv.gz' --output "outputs/baysor"

ERROR: LoadError: MethodError: no method matching tryparse(::Type{Symbol}, ::String)

Closest candidates are:
  tryparse(::Type{Union{}}, ::Any...; kwargs...)
   @ Base parse.jl:257
  tryparse(::Type{FilePathsBase.PosixPath}, ::AbstractString)
   @ FilePathsBase ~/.julia/packages/FilePathsBase/Laclt/src/posix.jl:15
  tryparse(::Type{Float16}, ::AbstractString)
   @ Base parse.jl:302
  ...

Stacktrace:
 [1] command_main(ARGS::Vector{String})
   @ Baysor ~/.julia/packages/Comonicon/F3QqZ/src/codegen/julia.jl:490
 [2] command_main()
   @ Baysor ~/.julia/packages/Comonicon/F3QqZ/src/codegen/julia.jl:90
 [3] top-level scope
   @ ~/.julia/bin/baysor:15
in expression starting at /dss/dsshome1/0C/go76saz2/.julia/bin/baysor:15

**Comment by marzaidi** [comment] 2024-09-25 11:11
OS:
Linux

Command:
baysor run -x x_location -y y_location -z z_location -g feature_name -m 15 '~/transcripts.csv.gz' --output "outputs/baysor"

ERROR: LoadError: MethodError: no method matching tryparse(::Type{Symbol}, ::String)

Closest candidates are:
tryparse(::Type{Union{}}, ::Any...; kwargs...)
@ Base parse.jl:257
tryparse(::Type{FilePathsBase.PosixPath}, ::AbstractString)
@ FilePathsBase ~/.julia/packages/FilePathsBase/Laclt/src/posix.jl:15
tryparse(::Type{Float16}, ::AbstractString)
@ Base parse.jl:302
...

Stacktrace:
[1] command_main(ARGS::Vector{String})
@ Baysor ~/.julia/packages/Comonicon/F3QqZ/src/codegen/julia.jl:490
[2] command_main()
@ Baysor ~/.julia/packages/Comonicon/F3QqZ/src/codegen/julia.jl:90
[3] top-level scope
@ ~/.julia/bin/baysor:15
in expression starting at /dss/dsshome1/0C/go76saz2/.julia/bin/baysor:15

**Comment by VPetukhov** [comment] 2024-11-19 11:55
This is fixed in v0.7.1.

**Closed by VPetukhov** 2024-11-19 11:55 UTC
Labels: duplicate
