### ISSUE TITLE
BUG: segmentation_polygon.json produce polygon with only 2 points

### ISSUE THREAD

**Issue by giacuong171** [kharchenkolab/Baysor#132] opened 2024-08-26 13:28 UTC
Hi Baysor Team,

Firstly, I want to thank you for creating such a fantastic tool. I use Baysor to generate segmentations from molecular cartography images. However, I've encountered an issue while reading the segmentation_polygon.json file with GeoPandas. The error occurs because some polygons in the file have only two points.

I've attached the segmentation_polygons.json file for your reference. As an example, the second polygon in the file demonstrates this issue.

I used this docker for running baysor with apptainer. 

> docker://maximilianheeg/baysor:v0.6.2

[segmentation_polygons.json](https://github.com/user-attachments/files/16749128/segmentation_polygons.json)

**Comment by VPetukhov** [comment] 2024-08-27 12:49
Hi @giacuong171 , that's a duplicate of https://github.com/kharchenkolab/Baysor/issues/103 . Will be fixed in the next release, hopefully this week.

**Closed** 2024-08-27 12:50 UTC
Labels: duplicate
