### ISSUE TITLE
inconsistent number of cells between the output files

### ISSUE THREAD

**Issue by MobiTobi** [kharchenkolab/Baysor#15] opened 2021-06-14 13:08 UTC
The number of cell boundaries in  `segmentation_polygons.json` far exceeds  the number of cells in `segmentation.csv` 
and `segmentation_cell_stats.csv`.
For example one of my runs produced  4013 polygons but only 2430 cells.

I would like to filter the boundaries that I plot with the diagnostics information in `segmentation_cell_stats.csv`, but due to the different numbers of elements they contain I cannot match the diagnostics information with the cell boundaries :(

The expected behaviour would be one polygon for each cell that baysor finds.

**Comment by VPetukhov** [comment] 2021-06-24 19:51
In the current version, polygons only roughly correspond to cells, unfortunately. The task of drawing polygons based on a set of points is ill-defined, and all solutions that I checked require some amount of parameter tuning. So in the current version, polygons may be drawn around empty holes in cells (showing their "inner boundaries"), or in rare cases one cell may have several polygons attached to it. There is a fix, which I'm going to implement in the next release, so each cell should only have the best-matching polygon, though I'm not sure if the solution would work as intended.

**Comment by jameswm2** [comment] 2021-11-19 01:09
@VPetukhov 
Hi, If the polygons do not correspond to cells, how did you draw boundaries in your publication?

**Comment by VPetukhov** [comment] 2022-02-04 20:08
Note for myself: after estimating KDE boundaries, need to replace my custom MST-based algorithm with [Marching squares](https://www.juliabloggers.com/implementing-marching-squares/), maybe from [Contour.jl](https://github.com/JuliaGeometry/Contour.jl)

**Comment by teng-gao** [comment] 2023-03-16 00:25
Hi @VPetukhov, is this fixed in the current release? (Apologies for raising so many issues)

**Comment by MobiTobi** [comment] 2023-03-28 09:59
Hi @teng-gao,

I made a stand-alone python module to generate "cell-borders" from the Baysor clusters.
It reimplements the approach from Petukhov, but has a few quality of life improvements.
I wanted to publish it on github anyway but never got around to it.
Are you interested?

- parallelized so much shorter wall time
- direct control over parameters (grid size, threshold etc)
- polygon estimation decoupled from baysor clustering

**Comment by VPetukhov** [comment] 2023-04-20 12:11
Hi @MobiTobi , that would be very useful! I'm currently working on a tool set for spatial analysis in Python ([baysorpy](https://github.com/VPetukhov/baysorpy)), which also will wrap julia calls to Baysor. If it's fine with you, it would be very cool to add your method to the package. Or it can be a stand-alone app, then I would reference it and use as a dependency for baysorpy.

**Comment by VPetukhov** [comment] 2023-04-20 12:12
Regarding the main issue, I just released [v0.6](https://github.com/kharchenkolab/Baysor/releases/tag/v0.6.0), which resolves it, and also has a much faster triangulation-based method for polygon estimation (similar to ideas from [here](https://doi.org/10.1109/IVCNZ.2015.7761536)).

**Closed by VPetukhov** 2023-04-20 12:12 UTC
